server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true # Esto permite usar minúsculas en las rutas automáticas
      routes:
        - id: user-service-route
          uri: lb://USER-SERVICE  # 'lb://' le dice al Gateway: "Busca en Eureka y reparte la carga"
          predicates:
            - Path=/users/** # Todas las peticiones que empiecen con /users/ irán al MS de usuarios
          filters:
            - StripPrefix=1       # Quita la palabra '/users' antes de mandarlo al microservicio
