spring:
  kafka:
    bootstrap-servers: localhost:9092
management:
  endpoints:
    web:
      exposure:
        include: health,env,mappings,metrics
  endpoint:
    env:
      access: read-only
    mappings:
      access: read-only
