server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/streaming_user_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  kafka:
    consumer:
      group-id: user-service-group-v2
      # Usamos el ErrorHandlingDeserializer para evitar el bucle infinito
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        # Aquí definimos que el deserializador real es el de JSON
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: "com.streaming.user_service.infrastructure.kafka.SubscriptionEvent"
        spring.json.use.type.info.headers: false
